### ISSUE TITLE
Copy link does not work

### ISSUE THREAD

**Issue by tpichlak** [carldata/hydra-http#128]
Doesn’t appear to do anything currently. Ideally we need this to produce a URL containing all of the input parameters (channels, dates, and script). Is this possible

**Comment by klangner** [comment]
The problem here is not with the server routing, but with the front end (FE) routing.
 * When we start application we go to: /static/index/html
 * When the user click on Calculations. FE will go to '/calculations', but there is no route to "/calculations". It is internal URI used only by FE.

That's why when we later want to use links created by FE, the don't work.
Maybe FE should use links like '/static/index.html?path=/calculations'?
